/**
 * Verify a built AAB before it goes anywhere. Run with
 * `npm run check:aab -- ~/Downloads/otclearn-vc9.aab`.
 *
 * Ported from Cornerstone on 2026-09-25, the day this repo needed it: the first
 * 1.3.0 artifact was about to ship Hermes `250829098.0.14`, the build carrying
 * the memory regression that Cornerstone's versionCode 10 and 11 both shipped.
 * Nothing said so. `expo-doctor` reads the source tree, the build log reports
 * its own success, and neither opens the AAB — so the check has to.
 *
 * **The traps, each of which has actually bitten one of the two apps:**
 *
 * 1. **The engine is only in the artifact.** Read the build string out of
 *    `base/lib/arm64-v8a/libhermesvm.so` and fail on the known-bad one. Asserted
 *    as "not that one" rather than an exact match, so a later upgrade is not
 *    failed for moving forward.
 * 2. **This app's RevenueCat key is in the JS bundle, not in `extra`.** It comes
 *    from `EXPO_PUBLIC_REVENUECAT_ANDROID_KEY`, which Babel inlines at build
 *    time. Cornerstone keeps its key in `extra` and its checker looks there —
 *    looking in the wrong place reports a perfectly good build as keyless.
 * 3. **`index.android.bundle` is Hermes bytecode**, so `grep` treats it as
 *    binary: `-a` is mandatory, and without it every content check is a silent
 *    false negative.
 * 4. **Hermes stores any string containing a non-ASCII character as UTF-16LE.**
 *    "System follows your phone’s light or dark setting" is absent as UTF-8 and
 *    present as UTF-16LE, purely because of the apostrophe. Search both.
 * 5. **Match permissions on the `<uses-permission` element, not on the word
 *    "permission".** `com.android.vending.BILLING` does not contain it.
 * 6. **Anchor the test-key search**, or a string table's `…shortest_paths`
 *    abutting another token cries wolf on every clean build.
 *
 * `aapt2 dump xmltree` cannot read an AAB manifest — it is protobuf — so the
 * manifest comes from `bundletool`.
 */
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));

/** Read, never written here: a literal goes stale the moment the version moves. */
const APP_VERSION = JSON.parse(readFileSync(join(HERE, '..', 'app.json'), 'utf8'))
  .expo.version;

/** The Hermes build with the memory regression. See the header. */
const BAD_HERMES = '250829098.0.14';

/**
 * Anything outside this set means a dependency added a permission.
 * `DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION` is generated by the React Native
 * build, not declared by us.
 */
const EXPECTED_PERMISSIONS = [
  'android.permission.INTERNET',
  'android.permission.POST_NOTIFICATIONS',
  'android.permission.RECEIVE_BOOT_COMPLETED',
  'android.permission.VIBRATE',
  'com.android.vending.BILLING',
  'com.otclearn.app.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION',
];

/** Strings that must ship, each the only evidence of something that must work. */
const EXPECTED_STRINGS = [
  'otc_learn_pro', // the entitlement the app reads by exact string
  'light or dark setting', // the Theme row — dark mode is what 1.3.0 is
  'Delete account', // the in-app deletion Play requires of an app with accounts
];

/** Native modules that must be linked, read from the dex. */
const EXPECTED_DEX = [
  'com.revenuecat.purchases',
  'com.android.billingclient',
  'expo.modules.updates',
];

let failures = 0;
const check = (ok, label, detail = '') => {
  if (!ok) failures += 1;
  console.log(`  ${ok ? 'PASS' : 'FAIL'}  ${label}${detail ? `  ${detail}` : ''}`);
};

function main() {
  const aab = process.argv[2];
  if (!aab || !existsSync(aab)) {
    console.error('Usage: npm run check:aab -- <path to .aab>');
    process.exit(2);
  }

  const work = mkdtempSync(join(tmpdir(), 'checkaab-'));
  try {
    console.log(`Verifying ${aab}\n`);

    console.log('Manifest');
    const manifest = execFileSync(
      'bundletool',
      ['dump', 'manifest', `--bundle=${aab}`],
      {
        encoding: 'utf8',
        maxBuffer: 32 * 1024 * 1024,
      },
    );
    const versionCode = /android:versionCode="(\d+)"/.exec(manifest)?.[1];
    const versionName = /android:versionName="([^"]+)"/.exec(manifest)?.[1];
    check(!!versionCode, 'versionCode present', versionCode ?? '');
    check(
      versionName === APP_VERSION,
      `versionName is ${APP_VERSION}`,
      versionName ?? '(missing)',
    );

    // Trap 5: match the element, not the word.
    const declared = [
      ...manifest.matchAll(/<uses-permission[^>]*android:name="([^"]+)"/g),
    ].map((m) => m[1]);
    check(
      declared.includes('com.android.vending.BILLING'),
      'com.android.vending.BILLING declared',
      '(Play requires it for subscriptions)',
    );
    const unexpected = declared.filter((p) => !EXPECTED_PERMISSIONS.includes(p));
    const missing = EXPECTED_PERMISSIONS.filter((p) => !declared.includes(p));
    check(
      unexpected.length === 0,
      'no unexpected permissions',
      unexpected.join(', '),
    );
    check(
      missing.length === 0,
      'no expected permission missing',
      missing.join(', '),
    );
    check(
      manifest.includes('android:autoVerify="true"'),
      'App Links autoVerify filter present',
    );

    execFileSync('unzip', ['-q', '-o', aab, '-d', work]);

    // Trap 1: the engine, read from the artifact.
    console.log('\nHermes (read from the artifact, never from the tooling)');
    const enginePath = join(work, 'base', 'lib', 'arm64-v8a', 'libhermesvm.so');
    if (existsSync(enginePath)) {
      const found = [
        ...new Set(
          [
            ...readFileSync(enginePath)
              .toString('latin1')
              .matchAll(/25\d{7}\.\d+\.\d+/g),
          ].map((m) => m[0]),
        ),
      ];
      check(
        found.length > 0,
        'Hermes build string found',
        found.join(', ') || 'none',
      );
      check(
        !found.includes(BAD_HERMES),
        `not the ${BAD_HERMES} regression`,
        found.join(', '),
      );
    } else {
      check(false, 'libhermesvm.so present', enginePath);
    }

    // Traps 2, 3, 4, 6: content, in the bundle, in both encodings.
    console.log('\nContent (Hermes bytecode — searched as UTF-8 and UTF-16LE)');
    const bundle = readFileSync(
      join(work, 'base', 'assets', 'index.android.bundle'),
    );
    const occurrences = (term) => {
      const utf8 = bundle.toString('latin1').split(term).length - 1;
      const utf16 =
        bundle
          .toString('latin1')
          .split(Buffer.from(term, 'utf16le').toString('latin1')).length - 1;
      return { utf8, total: utf8 + utf16 };
    };

    const key = /goog_[A-Za-z0-9]{10,}/.exec(bundle.toString('latin1'))?.[0];
    check(
      !!key,
      'RevenueCat production key present in the bundle',
      key ?? '(ABSENT)',
    );

    const testKeys = [
      ...new Set(
        [
          ...readFileSync(join(work, 'base', 'assets', 'index.android.bundle'))
            .toString('latin1')
            .matchAll(/\btest_[A-Za-z0-9]{12,}/g),
        ].map((m) => m[0]),
      ),
    ];
    check(
      testKeys.length === 0,
      'no RevenueCat test key in the bundle',
      testKeys.join(', '),
    );

    for (const term of EXPECTED_STRINGS) {
      const { utf8, total } = occurrences(term);
      check(
        total > 0,
        `"${term}" ships`,
        total ? `as ${utf8 ? 'UTF-8' : 'UTF-16LE'}` : '0 hits',
      );
    }

    console.log('\nNative modules (dex)');
    for (const symbol of EXPECTED_DEX) {
      const hit = execFileSync(
        'sh',
        [
          '-c',
          `grep -rla ${JSON.stringify(symbol)} ${JSON.stringify(join(work, 'base', 'dex'))} | head -1`,
        ],
        { encoding: 'utf8' },
      ).trim();
      check(hit !== '', `${symbol} linked`);
    }

    console.log(
      failures === 0
        ? '\nAll checks passed. This artifact is safe to upload.'
        : `\n${failures} check(s) failed. Do not upload this artifact.`,
    );
    process.exit(failures === 0 ? 0 : 1);
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
}

main();
